scheme("LiShu")
project("./LiShu.xcodeproj")

devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro"
])

languages([
  "zh-Hans"
])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
override_status_bar(true)
stop_after_first_error(true)
reinstall_app(true)
erase_simulator(true)
localize_simulator(true)
number_of_retries(1)
